### ISSUE TITLE
Performance with large amount of databases is poor.

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla-docker#10]
While a small performance loss is acceptable for the benefits of using a container, all my sites seemed to crawl to a halt once I imported a ~4GB of data across multiple databases in the datastorage volume (3-6 second response times). This is not an issue with using MySQL outside of Docker on MacOS 10.12.

I'm guessing the slowdown is could be partially alleviated by tuning the MySQL configuration a little bit, but is likely due to the way the datastorage volume is mounts the filesystem. I'm not really sure though.

Possible Solutions:

- Improve the docker setup/tune MySQL.
- Allow using the docker container, but with a native MySQL instance.

**Comment by DaazKu** [comment]
This seems to be a High Sierra problem: https://github.com/docker/for-mac/issues/1810#issuecomment-337886906
I rested with the same dump and I was able to restore it in 28m and I saw absolutely no performance downgrade.

**Comment by DaazKu** [comment]
Seems to have improved. Still not perfect though.

**Comment by DaazKu** [comment]
Doesn't seem to be an issue for normal development usage.
