### ISSUE TITLE
Windows Setup

### ISSUE THREAD

**Issue by csprance** [vanilla/vanilla-docker#16]
I see there is a mac-setup.sh script to set it up for a mac.

Any chance to get a windows based version of this script

**Comment by DaazKu** [comment]
Unfortunately, unless someone makes a PR, no.

Here is what you need to do to replicate what the script does though:

### Update /etc/hosts (Mendatory)

Add the following lines in `C:\Windows\System32\Drivers\etc\hosts`

```
127.0.0.1 database
127.0.0.1 dev.vanilla.localhost
127.0.0.1 sso.vanilla.localhost
127.0.0.1 vanilla.test
```

### Create a dedicated volume for the database (Mendatory)

Running this in the command line should do it:
`docker volume create --name=datastorage --label="Persistent data storage"`

### Add a loopback alias (Currently only used for xdebug)

See https://stackoverflow.com/questions/8944860/how-to-create-an-ip-alias-on-windows

The alias IP is `192.0.2.1`

Once that is done you can ping that ip to make sure it works properly.

### Install the custom certificate for dev.vanilla.localhost

This should help you do that:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754489(v=ws.11)
