### ISSUE TITLE
Upgrade to PHP 7.3

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla-docker#43]
To ensure that our development environment can always fix issues with the latest version of PHP it would be great to see an upgrade to PHP 7.3 which has now been released.

**Comment by DaazKu** [comment]
Unfortunately this will have to wait because xdebug and memcached are not yer ready to support PHP 7.3.

xdebug release 2.7.0 is in beta1 which is a good sign. https://pecl.php.net/package/xdebug
memcached has nothing though. https://pecl.php.net/package/memcached

**Comment by DaazKu** [comment]
You can use `feature/php-73` if you want to try PHP 7.3 without memcached.

**Comment by tburry** [comment]
Okay. Can we leave this open  everything is ready?

**Comment by DaazKu** [comment]
Yeah. This issue will close only when the PR which is WIP will be merged.
This will happen when memcached and xdebug will be released on PECL
