### ISSUE TITLE
yarn error on composer install

### ISSUE THREAD

**Issue by teglia** [vanilla/vanilla-docker#49]
Hi,

When doing the initial "composer install" as dictated in the local installation directions, I get the following error after all of the "Installing" and suggestions:

```
Generating autoload files
> Vanilla\Setup\ComposerHelper::postUpdate

Installing core node_modules
Usage: yarn [options]

yarn: error: no such option: --pure-lockfile
Installing core node_modules failed
```

I am not sure what is causing this, I can't see anything in the composer.json that would be the cause. Help?

**Comment by teglia** [comment]
Had the wrong version of Yarn installed.

**Comment by charrondev** [comment]
I'm glad you got it figured out. We have installation of build tooling, and compilation of the forum assets as a post install script for composer (See `Vanilla\Setup\ComposerHelper`).

I've contemplated moving the build steps inside of the docker container, but it's not particularly conducive to local development (slower mostly) and that's all this image is used for at the moment for us.

**Comment by teglia** [comment]
That's cool. Probably faster is better. Currently, my composer install is just hanging, for about 45 minutes now, just after:
`sudo apt-get update && sudo apt-get install yarn`

**Comment by charrondev** [comment]
It definitely shouldn't take that long. Full builds run in ~5 minutes on my local machine.

**Comment by teglia** [comment]
Giving that a shot, much more activity on the screen! Then it all just stopped, Shows this:

```
$ yarn build
yarn run v1.15.2
$ ts-node -P build/tsconfig.json build/scripts/build.ts
Installing node modules for directory: /mnt/c/repos/vanilla-project/vanilla/plugins/rich-editor
Installing node modules for directory: /mnt/c/repos/vanilla-project/vanilla/plugins/swagger-ui
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
✔ success polyfill compiled in 27s 972ms

Compiling

● admin █████████████████████████ chunk asset optimization (92%) TerserPlugin


● forum █████████████████████████ chunk asset optimization (92%) TerserPlugin


● knowledge █████████████████████████ chunk asset optimization (92%) TerserPlugin


● polyfill


```

**Comment by teglia** [comment]
Apparently there are some known issues in other projects with Yarn building on Windows Subsystem Linux. Not sure what causes that though, some people make it work, digging into that.

**Comment by charrondev** [comment]
This is definitely a point in favour of trying to move the build into the container (for consistency).

These rough edges around WSL are a little disappointing, but I'll be interested to know what comes of your digging.

**Comment by DaazKu** [comment]
https://github.com/vanilla/vanilla-docker/issues/77
