### ISSUE TITLE
'/srv/vanilla-repositories/vanilla' is not a directory

### ISSUE THREAD

**Issue by RikdeBoer** [vanilla/vanilla-docker#54]
Followed the READ.me. All fine up to and including step 12.
Then on step 13:

$ docker-compose up --build
....
Successfully tagged vanilla-docker_httpd:latest
Recreating database ... done
Recreating php-fpm  ... done
Recreating nginx    ... done
Recreating httpd    ... done
Attaching to database, php-fpm, httpd, nginx
php-fpm     | Updating certificates in /etc/ssl/certs...
httpd       | AH00526: Syntax error on line 48 of /usr/local/apache2/conf/httpd.conf:
httpd       | DocumentRoot '/srv/vanilla-repositories/vanilla' is not a directory, or is not readable
httpd exited with code 1

What am i missing?
What do I need to do in addition to the instructions?

**Comment by zentrope** [comment]
This can occur if you don't name the directories `vanilla` and `vanilla-docker`.

**Comment by charrondev** [comment]
I'm going to close this as zentrope has the correct answer. `nginx` is configured to look in this specific directory.

You can add extra nginx configs, but the default installation expects that you keep things named the same as the repos.
