### ISSUE TITLE
Make sphinx have a proper conf.d directory

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla-docker#59]
Currently, the sphinx config muse be a single sphinx.conf within the conf.d directory. A single sphinx file is difficult to use, is not compatible with our standard sphinx templates, and is not the way a conf.d directory is supposed to be structured. The changes I would like to see are the following:

1. A sphinx.conf outside of the conf.d directory that includes everything in the conf.d directory.
2. Sphinx is configured to use the above sphinx.conf file.

**Comment by charrondev** [comment]
I would like to see the ability to just use the templates directly. As an example, in our test setup for travis we compile and nginx template. We should be doing the same here.

@DaazKu could you share the script you guys use to compile the sphinx templates on infra?

**Comment by tburry** [comment]
The compiling of templates would be the next step. That, however is not within the scope of this issue.

I already made a command line tool to compile based on a JSON and could easily extend it for easier CLI access. The templates are all just mustache templates so compiling them is something developers can do.
