### ISSUE TITLE
Issues with new localhost 

### ISSUE THREAD

**Issue by patelsb** [vanilla/vanilla-docker#70]
Hello! I got a new laptop at work, and I was setting up my new localhost, and I ran into some issues. I use docker to set up my localhost. I used home-brew to install composer, and node.
When I got our repository, and ran it everything went fine. Then I went inside Vanilla-docker and ran the sudo command, and then ran docker-compose up and I would get this
<img width="815" alt="Screen Shot 2019-11-26 at 1 53 54 PM" src="https://user-images.githubusercontent.com/40374516/70254711-876ccb80-1753-11ea-835c-98c53c7ddc18.png">
Then I followed what it said about having creating the volume with vanilla data but once I did that I got this
<img width="1112" alt="Screen Shot 2019-11-26 at 1 48 43 PM" src="https://user-images.githubusercontent.com/40374516/70254746-9784ab00-1753-11ea-9346-b03062003459.png">
And when I checked my dev.localhost I would get this error message
<img width="1255" alt="Screen Shot 2019-11-26 at 2 01 44 PM" src="https://user-images.githubusercontent.com/40374516/70254794-a8cdb780-1753-11ea-9a62-6e82c7b81dc8.png">
Do you guys know what is going on? Did I miss a step?
Thank you guys!

**Comment by patelsb** [comment]
Also here is what my docker.compose.yml looks like 
<img width="1920" alt="Screen Shot 2019-12-04 at 11 51 01 AM" src="https://user-images.githubusercontent.com/40374516/70254996-03671380-1754-11ea-8f11-760893e83968.png">
<img width="1920" alt="Screen Shot 2019-12-04 at 11 51 18 AM" src="https://user-images.githubusercontent.com/40374516/70254998-0530d700-1754-11ea-80e5-58cc3e87df83.png">

**Comment by charrondev** [comment]
I'd recommend using the default config and adding custom overrides on top and see if that resolves it.

I use this as my startup script.

```shell
#!/usr/bin/env bash

cd ~/srv/vanilla-docker
docker-compose \
-f ~/srv/vanilla-docker/docker-compose.yml \ # PHP & Nginx
-f ~/srv/vanilla-docker/docker-compose.override.yml \ # Database
-f ~/srv/vanilla-docker/custom.service-nfs.yml \ # Custom file-system mapping
-f ~/srv/vanilla-docker/service-memcached.yml \ # Extra services
-f ~/srv/vanilla-docker/service-sphinx.yml \
up --build -d # -d To run in the background.
```

**Comment by patelsb** [comment]
Where did you put this? In your docker-compose.yml?

**Comment by charrondev** [comment]
I made a custom bash script called `startDocker.sh` and run that, but you could could also just copy paste it into your terminal (leaving off the `custom.service.yml` of course).

The whole custom thing is how you can add custom configuration on top of the base one. Basically docker compose merges all the configs together before running, so this way you don't have to modify at all the included `docker-compose.yml` & `docker-compose.override.yml` files.

**Comment by patelsb** [comment]
I just tried that, but I don't have a docker-compose.override.yml so I took it out, and it didn't work. It just ran but stoped. Should I have a docker-compose.override.yml?
