### ISSUE TITLE
Composer install not running, error 127 

### ISSUE THREAD

**Issue by patelsb** [vanilla/vanilla-docker#71]
Hi! I am starting up a new localhost and using this repository. I got vanilla/vanilla, and when I did a composer install I would get this error

 5 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/simhranpatel/community/vanilla/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/Users/simhranpatel/community/vanilla/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /Users/simhranpatel/community/vanilla/node_modules/fibers
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
/bin/sh: nodejs: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Reading it through I thought it meant I had an older version of node and yarn. I made sure they were up to date by running node -v, and yarn -v. 

You think you guys can help me out?

**Comment by LaurenOLoughlen** [comment]
@charrondev I am not sure how to proceed with this issue. Would you be able to assist us? Thanks.

**Comment by patelsb** [comment]
Hello, I figured out the problem. Apparently you should not use the latest node version. I used node 10 and it worked.
